import argparse

def create_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model', type=str, default='dino')
    parser.add_argument('--dataset', default='vindr', type=str)
    parser.add_argument('--dataset_cat', type=int, default=1)
    parser.add_argument('--data_pct', type=float, default=1.0)
    parser.add_argument('--stride', type=int, default=1)
    parser.add_argument('--epochs', default=50, type=int)
    parser.add_argument('--warmup_epochs', default=5, type=int)
    parser.add_argument('--early_stop', type=int, default=20)
    parser.add_argument('--batch_size', default=256, type=int,
                        help='Batch size per GPU (effective batch size is batch_size * accum_iter * # gpus')
    parser.add_argument('--lr', type=float, default=1e-4)
    parser.add_argument('--min_lr', type=float, default=1e-6)
    parser.add_argument('--pretrained', type=str, default='')
    parser.add_argument('--eval', action='store_true', help='Perform evaluation only')
    parser.add_argument('--accum_iter', default=1, type=int,
                        help='Accumulate gradient iterations (for increasing the effective batch size under memory constraints)')
    parser.add_argument('--eval_freq', type=int, default=1)
    parser.add_argument('--input_size', default=224, type=int,
                        help='images input size')
    parser.add_argument('--resize_size', default=256, type=int,
                        help='images resize size')
    parser.add_argument('--color_jitter', type=float, default=0.5)
    parser.add_argument('--norm_type', type=str, default='default')
    parser.add_argument('--no_stdout', action='store_true', default=False)
    parser.add_argument('--seed', type=int, default=42)
    parser.add_argument('--rot', type=float, default=0)
    parser.add_argument('--num_workers', default=10, type=int)
    parser.add_argument('--clip_grad', type=float, default=None)
    parser.add_argument('--print_freq', default=10, type=int)
    parser.add_argument('--output_dir', type=str, default='output')
    parser.add_argument('--exp_name', type=str, default='exp')
    parser.add_argument('--weight_decay', type=float, default=0.05)
    parser.add_argument('--layer_decay', type=float, default='1.0')
    parser.add_argument('--drop_path', type=float, default=0.0)
    parser.add_argument('--dropout', type=float, default=0.0)
    parser.add_argument('--save_mode', type=str, default='best')
    parser.add_argument('--resume', type=str, default='')
    parser.add_argument('--proj_type', type=str, default='mlp')
    parser.add_argument('--lr_sched', type=str, default='cos')
    parser.add_argument('--ar_skip', type=int, default=0) # skip first and last frames to align with seq model
    parser.add_argument('--equi_dim', type=int, default=1024)
    parser.add_argument('--ema', type=float, default=0.999)
    parser.add_argument('--lam_consist', type=float, default=1.0)
    parser.add_argument("--sim-coeff", type=float, default=10.0)
    parser.add_argument("--std-coeff", type=float, default=10.0)
    parser.add_argument("--cov-coeff", type=float, default=1.0)
    parser.add_argument('--cond_mode', type=str, default='matrix')
    parser.add_argument('--weight_mode', type=str, default='')
    parser.add_argument('--freeze_backbone', action='store_true', default=False)
    parser.add_argument('--lam_world', type=float, default=1.0)
    parser.add_argument('--backbone_lr_scale', type=float, default=1.0)
    parser.add_argument('--aug_type', type=str, default='default')
    parser.add_argument('--label_scale', type=float, default=200)
    parser.add_argument('--case_num_repeat', type=int, default=64)
    parser.add_argument('--set_case_id', type=str, default=[], nargs='*')
    parser.add_argument('--set_case_id_eval', type=str, default=[], nargs='*')
    parser.add_argument('--world_type', type=str, default='hyper')
    parser.add_argument('--action_noise', type=float, default=0.0)
    parser.add_argument('--buffer_size', type=int, default=3)
    parser.add_argument('--weighted_loss', action='store_true', default=False)
    parser.add_argument('--reference_model', type=str, default='')
    parser.add_argument('--cross_val_fold', type=int, default=-1)
    parser.add_argument('--nfolds', type=int, default=5)
    parser.add_argument('--ensemble', type=str, nargs='*', default=[])
    parser.add_argument('--loss_pred_hidden_dim', type=int, default=128)
    parser.add_argument('--loss_pred_mode', type=str, default='cls_feat_pred')
    parser.add_argument('--force_frame_sample', action='store_true', default=False)
    parser.add_argument('--num_frames', type=int, default=5)
    parser.add_argument('--ens_mode', type=str, default='avg')
    parser.add_argument('--agent_type', type=str, default='past')
    parser.add_argument('--train_seq_prob', type=float, default=0)
    parser.add_argument('--exp_alpha', type=float, default=0.25)
    parser.add_argument('--weight_last', type=float, default=1.0)
    parser.add_argument('--pred_last', action='store_true', default=False)
    parser.add_argument('--force_sampling', type=str, default=None)
    parser.add_argument('--num_global_best', type=int, default=None)
    parser.add_argument('--ar_train', action='store_true', default=False)
    parser.add_argument('--equal_loss', action='store_true', default=False)
    parser.add_argument('--single_plane', type=int, default=0)
    parser.add_argument('--debug', action='store_true', default=False)
    parser.add_argument('--gnn_cfg', type=str, default='')
    parser.add_argument('--zero_act', action='store_true', default=False)
    return parser