data:
  batch_size: 256
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224
  image_folder: modified_dataset
  num_workers: 16
  pin_mem: true
  root_path: /data/yueyang
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  folder: outputs_jepa
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_pred_masks: 4
  patch_size: 16
  pred_mask_scale:
  - 0.15
  - 0.2
  num_plane_to_select: 1
  num_enc_masks: 1
meta:
  copy_data: false
  model_name: vit_small
  pred_depth: 6
  pred_emb_dim: 384
  pred_num_heads: 4
  pred_mlp_ratio: 2
  load_checkpoint: false
  read_checkpoint: null
  use_bfloat16: true
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 300
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.0005
  start_lr: 0.0001
  warmup: 40
  weight_decay: 0.04
